packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@remix-run/dev": ^2.13.1
  "@remix-run/node": ^2.13.1
  "@remix-run/react": ^2.13.1
  "@remix-run/serve": ^2.13.1
  "@tokenami/css": ^0.0.68
  "@tokenami/dev": ^0.0.68
  "@tokenami/ts-plugin": ^0.0.68
  "@types/node": ^22.7.5
  commonality: ^0.2.63
  commonality-checks-recommended: ^0.0.40
  react: 19.0.0-rc-09111202-20241011
  react-dom: 19.0.0-rc-09111202-20241011
  "@types/react": npm:types-react@19.0.0-rc.1
  "@types/react-dom": npm:types-react-dom@19.0.0-rc.1
  typescript: ^5.6.3
