import { createConfig } from "@tokenami/css";

// cspell:ignore segoe, noto, menlo, consolas, focusring

export const config = createConfig({
	globalStyles: {
		"*, *::before, *::after": {
			border: 0,
			boxSizing: "border-box",
			margin: 0,
			padding: 0,
		},
		"::-webkit-inner-spin-button, ::-webkit-outer-spin-button": {
			height: "auto",
		},
		"::placeholder": {
			color: "color-mix(in srgb, currentColor 50%, transparent)",
			opacity: "1",
		},
		"::webkit-search-decoration": {
			WebkitAppearance: "none",
		},
		":-moz-focusring": {
			outline: "auto",
		},
		":-moz-ui-invalid": {
			boxShadow: "none",
		},
		":root": {
			/* set up default vars for var(text_*) tokens */
			["--font-family" as string]: `ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"`,
			["--font-stretch" as string]: "normal",
			["--font-style" as string]: "normal",
			["--font-variant" as string]: "normal",
			["--font-weight" as string]: "normal",
		},
		'[hidden]:not([hidden="until-found"])': {
			display: "none",
		},
		a: {
			color: "inherit",
			textDecoration: "inherit",
		},
		"abbr:where([title])": {
			textDecoration: "underline dotted",
		},
		"b, strong": {
			fontWeight: "bolder",
		},
		body: {
			lineHeight: "inherit",
		},
		"button, input, optgroup, select, textarea, ::file-selector-button": {
			background: "transparent",
			color: "inherit",
			font: "inherit",
			fontFeatureSettings: "inherit",
			fontVariationSettings: "inherit",
			letterSpacing: "inherit",
		},
		'button, input:where([type="button"]), input:where([type="reset"]), input:where([type="submit"]), ::file-selector-button ':
			{
				appearance: "button",
			},
		"code, kbd, samp, pre": {
			["--font-family" as string]: `ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace`,
			fontFamily: "var(--font-family)",
			fontFeatureSettings: "normal",
			fontSize: "1em",
			fontVariationSettings: "normal",
		},
		"h1, h2, h3, h4, h5, h6": {
			fontSize: "inherit",
			fontWeight: "inherit",
		},
		hr: {
			borderTopWidth: "1px",
			color: "inherit",
			height: "0",
		},
		"html, :host": {
			fontFamily: "var(--font-family)",
			fontFeatureSettings: "normal",
			fontVariationSettings: "normal",
			lineHeight: 1.5,
			tabSize: 4,
			WebkitTapHighlightColor: "transparent",
			WebkitTextSizeAdjust: "100%",
		},
		"img, svg, video, canvas, audio, iframe, embed, object": {
			display: "block",
			verticalAlign: "middle",
		},
		'input:where(:not([type="button"], [type="reset"], [type="submit"])), select, textarea': {
			border: "1px solid",
		},
		"ol, ul, menu": {
			listStyle: "none",
		},
		progress: {
			verticalAlign: "baseline",
		},
		small: {
			fontSize: "80%",
		},
		sub: {
			bottom: "-0.25em",
		},
		"sub, sup": {
			fontSize: "75%",
			lineHeight: 0,
			position: "relative",
			verticalAlign: "baseline",
		},
		summary: {
			display: "list-item",
		},
		sup: {
			top: "-0.5em",
		},
		table: {
			borderCollapse: "collapse",
			borderColor: "inherit",
			textIndent: 0,
		},
		textarea: {
			resize: "vertical",
		},
	},
	grid: "0.25rem",
	include: [],
	properties: {
		"accent-color": ["color"],
		animation: ["anim"],
		"animation-timing-function": ["ease"],
		background: ["color", "surface"],
		"background-color": ["color"],
		"background-image": ["surface"],
		"background-position": ["grid"],
		"background-position-x": ["grid"],
		"background-position-y": ["grid"],
		"block-size": ["grid", "size"],
		border: ["border"],
		"border-block": ["border"],
		"border-block-color": ["color"],
		"border-block-end": ["border"],
		"border-block-end-color": ["color"],
		"border-block-end-style": ["line-style"],
		"border-block-start": ["border"],
		"border-block-start-color": ["color"],
		"border-block-start-style": ["line-style"],
		"border-block-style": ["line-style"],
		"border-bottom": ["border"],
		"border-bottom-color": ["color"],
		"border-bottom-left-radius": ["radii"],
		"border-bottom-right-radius": ["radii"],
		"border-bottom-style": ["line-style"],
		"border-color": ["color"],
		"border-end-end-radius": ["radii"],
		"border-end-start-radius": ["radii"],
		"border-inline": ["border"],
		"border-inline-color": ["color"],
		"border-inline-end": ["border"],
		"border-inline-end-color": ["color"],
		"border-inline-end-style": ["line-style"],
		"border-inline-start": ["border"],
		"border-inline-start-color": ["color"],
		"border-inline-start-style": ["line-style"],
		"border-inline-style": ["line-style"],
		"border-left": ["border"],
		"border-left-color": ["color"],
		"border-left-style": ["line-style"],
		"border-radius": ["radii"],
		"border-right": ["border"],
		"border-right-color": ["color"],
		"border-right-style": ["line-style"],
		"border-start-end-radius": ["radii"],
		"border-start-start-radius": ["radii"],
		"border-style": ["line-style"],
		"border-top": ["border"],
		"border-top-color": ["color"],
		"border-top-left-radius": ["radii"],
		"border-top-right-radius": ["radii"],
		"border-top-style": ["line-style"],
		bottom: ["grid"],
		"box-shadow": ["shadow"],
		"caret-color": ["color"],
		color: ["color"],
		"column-gap": ["grid"],
		"column-rule-color": ["color"],
		"column-rule-width": ["grid"],
		"column-width": ["grid", "size"],
		fill: ["color"],
		"flex-basis": ["grid", "size"],
		"font-family": ["font"],
		"font-size": ["font-size"],
		"font-weight": ["weight"],
		gap: ["grid"],
		height: ["grid", "size"],
		"inline-size": ["grid", "size"],
		inset: ["grid"],
		"inset-block": ["grid"],
		"inset-block-end": ["grid"],
		"inset-block-start": ["grid"],
		"inset-inline": ["grid"],
		"inset-inline-end": ["grid"],
		"inset-inline-start": ["grid"],
		left: ["grid"],
		"letter-spacing": ["tracking"],
		"line-height": ["leading"],
		margin: ["grid"],
		"margin-block": ["grid"],
		"margin-block-end": ["grid"],
		"margin-block-start": ["grid"],
		"margin-bottom": ["grid"],
		"margin-inline": ["grid"],
		"margin-inline-end": ["grid"],
		"margin-inline-start": ["grid"],
		"margin-left": ["grid"],
		"margin-right": ["grid"],
		"margin-top": ["grid"],
		"max-block-size": ["grid", "size"],
		"max-height": ["grid", "size"],
		"max-inline-size": ["grid", "size"],
		"max-width": ["grid", "size"],
		"min-block-size": ["grid", "size"],
		"min-height": ["grid", "size"],
		"min-inline-size": ["grid", "size"],
		"min-width": ["grid", "size"],
		opacity: ["alpha"],
		"outline-color": ["color"],
		padding: ["grid"],
		"padding-block": ["grid"],
		"padding-block-end": ["grid"],
		"padding-block-start": ["grid"],
		"padding-bottom": ["grid"],
		"padding-inline": ["grid"],
		"padding-inline-end": ["grid"],
		"padding-inline-start": ["grid"],
		"padding-left": ["grid"],
		"padding-right": ["grid"],
		"padding-top": ["grid"],
		right: ["grid"],
		"row-gap": ["grid"],
		"scroll-margin": ["grid"],
		"scroll-margin-bottom": ["grid"],
		"scroll-margin-left": ["grid"],
		"scroll-margin-right": ["grid"],
		"scroll-margin-top": ["grid"],
		"scroll-padding": ["grid"],
		"scroll-padding-bottom": ["grid"],
		"scroll-padding-left": ["grid"],
		"scroll-padding-right": ["grid"],
		"scroll-padding-top": ["grid"],
		stroke: ["color"],
		"text-decoration-color": ["color"],
		"text-shadow": ["shadow"],
		top: ["grid"],
		transition: ["transition"],
		"transition-timing-function": ["ease"],
		width: ["grid", "size"],
		"z-index": ["z"],
	},
	responsive: {},
	selectors: {
		active: "&:active",
		after: "&::after",
		before: "&::before",
		disabled: "&:disabled",
		even: "&:nth-child(even)",
		"first-child": "&:first-child",
		focus: "&:focus",
		"focus-visible": "&:focus-visible",
		"focus-within": "&:focus-within",
		hover: "&:hover",
		"last-child": "&:last-child",
		odd: "&:nth-child(odd)",
		placeholder: "&::placeholder",
	},
	theme: {
		alpha: {},
		anim: {},
		border: {},
		color: {
			test: "blue",
		},
		ease: {},
		"font-size": {},
		leading: {},
		"line-style": {},
		radii: {},
		shadow: {},
		size: {},
		surface: {},
		tracking: {},
		transition: {},
		weight: {},
		z: {},
	},
});
