name: Setup
description: Setup environment specific to this monorepo, including e.g. pnpm and node

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # pin@v4

    - name: Install node
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # pin@v4
      with:
        node-version-file: "package.json"
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm i
